sudo: required 
services: 
    - docker 

before_install:
    - docker build -t babatundeola/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true babatundeola/react-test npm test -- --coverage

after_success:
    - docker build -t babatundeola/multi-client ./client 
    - docker build -t babatundeola/multi-ngx ./nginx 
    - docker build -t babatundeola/multi-server ./server
    - docker build -t babatundeola/multi-worker ./worker
    # Login to the docker CLI 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push babatundeola/multi-client
    - docker push babatundeola/multi-nginx
    - docker push babatundeola/multi-server
    - docker push babatundeola/multi-worker